service: review-ojisan

provider:
  name: aws
  runtime: go1.x

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  hello:
    handler: bin/review-ojisan
    events:
      - http:
          path: review-ojisan
          method: post
